export enum CommonSpaceType {
  SALON_EVENTOS = 'SALON_EVENTOS',
  GIMNASIO = 'GIMNASIO',
  PISCINA = 'PISCINA',
  QUINCHO = 'QUINCHO',
  SALA_MULTIUSO = 'SALA_MULTIUSO',
  CANCHA_DEPORTIVA = 'CANCHA_DEPORTIVA',
  JARDIN = 'JARDIN',
  PLAYGROUND = 'PLAYGROUND',
}
