export enum ReservationType {
  TRABAJO = 'TRABAJO',
  CELEBRACION = 'CELEBRACION',
  REUNION_FAMILIAR = 'REUNION_FAMILIAR',
  CUMPLEANOS = 'CUMPLEANOS',
  EVENTO_CORPORATIVO = 'EVENTO_CORPORATIVO',
  OTRO = 'OTRO',
}
